name: Disable Workflow Video

on: 
  push:
    branches: [ main ]

jobs:
  disable:
    runs-on: ubuntu-latest

    steps:
      - name: shivam
        run: echo "Diable Workflow Video Devops"

        
